"""Legacy wiki migration command.

`llm-wiki migrate` reconciles pages generated by older llm-wiki versions with
the current collision-aware naming rules.  Active canonical pages are
regenerated from source, old active pages are archived, and previous page
content is preserved under a Legacy Notes section.
"""

from __future__ import annotations

import os
import re
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

from .bootstrap_cmd import (
    _build_relationships,
    _generate_docker_md,
    _generate_entity_md,
    _generate_index_md,
    _generate_module_md,
    build_entity_page_map,
    build_module_page_map,
)
from .extract_cmd import get_docker_inventory, get_inventory
from .sync_cmd import SyncManifest
from ..config import DEFAULT_WIKI_DIR, validate_path
from ..services.io import read_md, write_md

LEGACY_MARKER = "<!-- llm-wiki-migrate:legacy-notes -->"
_MANAGED_DIRS = ("entities", "modules", "infrastructure")
_LINK_RE = re.compile(r"(\[[^\]]+\]\()([^)]+)(\))")
_HEADING_RE = re.compile(r"^#\s+(.+?)\s*$", re.MULTILINE)
_LOCATION_RE = re.compile(r"^\*\*Location:\*\*\s*`?(.+?):(\d+)`?\s*$", re.MULTILINE)
_PATH_RE = re.compile(r"^\*\*Path:\*\*\s*`?(.+?)`?\s*$", re.MULTILINE)


@dataclass(frozen=True)
class ExistingPage:
    """A currently active wiki page before migration."""

    kind: str
    path: Path
    rel: str
    stem: str
    content: str
    heading: str | None = None
    location_path: str | None = None
    location_line: int | None = None
    source_path: str | None = None


@dataclass(frozen=True)
class TargetPage:
    """A canonical page generated from the current source inventory."""

    kind: str
    stem: str
    rel: str
    content: str
    source_path: str | None = None
    entity_name: str | None = None
    line: int | None = None


@dataclass
class MigrationPlan:
    """Computed migration operations, shared by apply and dry-run paths."""

    archive_name: str
    targets: list[TargetPage]
    matches: dict[str, list[ExistingPage]] = field(default_factory=dict)
    unmatched: list[ExistingPage] = field(default_factory=list)
    link_map: dict[str, str] = field(default_factory=dict)
    index_content: str = ""
    manifest: SyncManifest | None = None


def _normalize_source_path(value: str | None, src_dir: str) -> str | None:
    """Normalize extracted markdown source paths to inventory-relative paths."""
    if not value:
        return None
    normalized = value.strip().strip("`").strip().strip('"').strip("'")
    normalized = normalized.replace("\\", "/")
    while normalized.startswith("./"):
        normalized = normalized[2:]

    candidate = Path(normalized)
    if candidate.is_absolute():
        try:
            return candidate.resolve().relative_to(Path(src_dir).resolve()).as_posix()
        except ValueError:
            return candidate.as_posix()
    return normalized


def _page_rel(path: Path, wiki_dir: Path) -> str:
    return path.relative_to(wiki_dir).as_posix()


def _read_existing_page(path: Path, wiki_dir: Path, src_dir: str) -> ExistingPage:
    content = read_md(path)
    rel = _page_rel(path, wiki_dir)
    kind = path.parent.name

    heading_match = _HEADING_RE.search(content)
    location_match = _LOCATION_RE.search(content)
    path_match = _PATH_RE.search(content)

    location_path: str | None = None
    location_line: int | None = None
    if location_match:
        location_path = _normalize_source_path(location_match.group(1), src_dir)
        location_line = int(location_match.group(2))

    source_path = _normalize_source_path(path_match.group(1), src_dir) if path_match else None

    return ExistingPage(
        kind=kind,
        path=path,
        rel=rel,
        stem=path.stem,
        content=content,
        heading=heading_match.group(1).strip() if heading_match else None,
        location_path=location_path,
        location_line=location_line,
        source_path=source_path,
    )


def _active_managed_pages(wiki_dir: Path, src_dir: str) -> list[ExistingPage]:
    pages: list[ExistingPage] = []
    for dirname in _MANAGED_DIRS:
        directory = wiki_dir / dirname
        if not directory.exists():
            continue
        for path in sorted(directory.glob("*.md")):
            if path.is_file():
                pages.append(_read_existing_page(path, wiki_dir, src_dir))
    return pages


def _build_targets(
    wiki_dir: Path,
    src_dir: str,
    inventory: dict,
    docker_inventory: dict,
) -> tuple[list[TargetPage], str, SyncManifest]:
    module_page_map = build_module_page_map(inventory)
    entity_page_map = build_entity_page_map(inventory)
    relationships = _build_relationships(inventory, module_page_map)

    targets: list[TargetPage] = []
    entity_names: list[str] = []
    module_entries: list[dict] = []
    infra_entries: list[dict] = []

    for filepath, file_data in inventory.items():
        module_page = module_page_map[filepath]
        file_entity_map = {
            cls["name"]: entity_page_map[(cls["name"], filepath)]
            for cls in file_data.get("classes", [])
        }

        module_entries.append({
            "name": module_page,
            "path": filepath,
            "docstring": file_data.get("module_docstring", ""),
        })
        targets.append(TargetPage(
            kind="modules",
            stem=module_page,
            rel=f"modules/{module_page}.md",
            content=_generate_module_md(filepath, file_data, file_entity_map),
            source_path=filepath,
        ))

        for cls in file_data.get("classes", []):
            entity_page = entity_page_map[(cls["name"], filepath)]
            entity_names.append(entity_page)
            targets.append(TargetPage(
                kind="entities",
                stem=entity_page,
                rel=f"entities/{entity_page}.md",
                content=_generate_entity_md(cls, filepath, relationships, module_page),
                source_path=filepath,
                entity_name=cls["name"],
                line=cls.get("line"),
            ))

    for docker_file, docker_info in docker_inventory.items():
        page_name = docker_file.replace("\\", "/").replace("/", "_").replace(".", "_")
        infra_entries.append({"name": page_name, "type": docker_info.get("type", "")})
        targets.append(TargetPage(
            kind="infrastructure",
            stem=page_name,
            rel=f"infrastructure/{page_name}.md",
            content=_generate_docker_md(docker_file, docker_info, module_page_map),
            source_path=docker_file,
        ))

    workflow_entries = _list_workflows(wiki_dir)
    index_content = _generate_index_md(
        entity_names,
        module_entries,
        workflow_entries or None,
        infra_entries or None,
    )
    manifest = SyncManifest.build_from_inventory(
        inventory,
        src_dir,
        entity_page_map,
        module_page_map,
    )
    return targets, index_content, manifest


def _list_workflows(wiki_dir: Path) -> list[dict]:
    workflow_dir = wiki_dir / "workflows"
    if not workflow_dir.exists():
        return []
    return [{"name": path.stem, "entry": ""} for path in sorted(workflow_dir.glob("*.md"))]


def _unique(values: list[TargetPage]) -> TargetPage | None:
    return values[0] if len(values) == 1 else None


def _build_match_lookups(targets: list[TargetPage]) -> dict[str, dict]:
    lookups: dict[str, dict] = {
        "by_rel": {target.rel: target for target in targets},
        "entities_by_path_name": {},
        "entities_by_name": {},
        "modules_by_source": {},
        "modules_by_source_stem": {},
        "modules_by_page_stem": {},
        "infra_by_source": {},
        "infra_by_page_stem": {},
    }

    for target in targets:
        if target.kind == "entities" and target.entity_name:
            lookups["entities_by_path_name"].setdefault(
                (target.source_path, target.entity_name), []
            ).append(target)
            lookups["entities_by_name"].setdefault(target.entity_name, []).append(target)
        elif target.kind == "modules":
            lookups["modules_by_source"][target.source_path] = target
            lookups["modules_by_source_stem"].setdefault(
                Path(target.source_path or "").stem, []
            ).append(target)
            lookups["modules_by_page_stem"].setdefault(target.stem, []).append(target)
        elif target.kind == "infrastructure":
            lookups["infra_by_source"][target.source_path] = target
            lookups["infra_by_page_stem"].setdefault(target.stem, []).append(target)
    return lookups


def _match_existing_page(page: ExistingPage, lookups: dict[str, dict]) -> TargetPage | None:
    if page.rel in lookups["by_rel"]:
        return lookups["by_rel"][page.rel]

    if page.kind == "entities":
        name = page.heading or page.stem.rsplit("_", 1)[-1]
        if page.location_path:
            exact = _unique(lookups["entities_by_path_name"].get((page.location_path, name), []))
            if exact:
                return exact
        return _unique(lookups["entities_by_name"].get(name, []))

    if page.kind == "modules":
        if page.source_path and page.source_path in lookups["modules_by_source"]:
            return lookups["modules_by_source"][page.source_path]
        canonical = _unique(lookups["modules_by_page_stem"].get(page.stem, []))
        if canonical:
            return canonical
        return _unique(lookups["modules_by_source_stem"].get(page.stem, []))

    if page.kind == "infrastructure":
        if page.source_path and page.source_path in lookups["infra_by_source"]:
            return lookups["infra_by_source"][page.source_path]
        return _unique(lookups["infra_by_page_stem"].get(page.stem, []))

    return None


def _build_migration_plan(wiki_dir: Path, src_dir: str) -> MigrationPlan:
    inventory = get_inventory(src_dir, deep=True)
    docker_inventory = get_docker_inventory(src_dir)
    targets, index_content, manifest = _build_targets(wiki_dir, src_dir, inventory, docker_inventory)
    lookups = _build_match_lookups(targets)
    target_rels = {target.rel for target in targets}
    plan = MigrationPlan(
        archive_name=f"migrate-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}",
        targets=targets,
        index_content=index_content,
        manifest=manifest,
    )

    for page in _active_managed_pages(wiki_dir, src_dir):
        target = _match_existing_page(page, lookups)
        if target:
            plan.matches.setdefault(target.rel, []).append(page)
            if page.rel != target.rel:
                plan.link_map[page.rel] = target.rel
        elif page.rel not in target_rels:
            plan.unmatched.append(page)

    return plan


def _existing_legacy_payload(page: ExistingPage, generated_content: str) -> str:
    content = page.content.strip()
    if not content or content == generated_content.strip():
        return ""
    if LEGACY_MARKER in page.content:
        return page.content.split(LEGACY_MARKER, 1)[1].strip()
    return content


def _merge_legacy_notes(target: TargetPage, pages: list[ExistingPage]) -> str:
    sections: list[str] = []
    for page in pages:
        payload = _existing_legacy_payload(page, target.content)
        if not payload:
            continue
        if payload.startswith("### From "):
            sections.append(payload)
        else:
            sections.append(f"### From `{page.rel}`\n\n{payload}")

    if not sections:
        return target.content

    return (
        target.content.rstrip()
        + "\n\n## Legacy Notes\n\n"
        + LEGACY_MARKER
        + "\n\n"
        + "\n\n".join(sections).rstrip()
        + "\n"
    )


def _archive_page(page: ExistingPage, wiki_dir: Path, archive_root: Path, dry_run: bool) -> None:
    dest = archive_root / page.rel
    print(f"  ARCHIVE {page.rel} -> {_page_rel(dest, wiki_dir)}")
    if dry_run:
        return
    dest.parent.mkdir(parents=True, exist_ok=True)
    write_md(dest, page.content)


def _remove_old_page(page: ExistingPage, dry_run: bool) -> None:
    if dry_run:
        return
    page.path.unlink(missing_ok=True)


def _write_page(wiki_dir: Path, rel: str, content: str, dry_run: bool) -> None:
    print(f"  WRITE {rel}")
    if dry_run:
        return
    path = wiki_dir / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    write_md(path, content)


def _is_legacy_path(path: Path, wiki_dir: Path) -> bool:
    try:
        return path.relative_to(wiki_dir).parts[:1] == ("legacy",)
    except ValueError:
        return False


def _active_markdown_pages(wiki_dir: Path) -> list[Path]:
    if not wiki_dir.exists():
        return []
    return [
        path for path in sorted(wiki_dir.rglob("*.md"))
        if path.is_file() and not _is_legacy_path(path, wiki_dir)
    ]


def _rewrite_links_in_content(content: str, page: Path, wiki_dir: Path, link_map: dict[str, str]) -> str:
    if not link_map:
        return content
    wiki_root = wiki_dir.resolve()

    def replace(match: re.Match[str]) -> str:
        prefix, url, suffix = match.groups()
        if url.startswith(("http://", "https://", "mailto:", "#")):
            return match.group(0)

        base_url, sep, anchor = url.partition("#")
        if not base_url:
            return match.group(0)

        try:
            target = (page.parent / base_url).resolve()
            old_rel = target.relative_to(wiki_root).as_posix()
        except ValueError:
            return match.group(0)

        new_rel = link_map.get(old_rel)
        if not new_rel:
            return match.group(0)

        relative = os.path.relpath(wiki_dir / new_rel, start=page.parent).replace(os.sep, "/")
        if sep:
            relative += f"#{anchor}"
        return f"{prefix}{relative}{suffix}"

    return _LINK_RE.sub(replace, content)


def _rewrite_active_links(wiki_dir: Path, link_map: dict[str, str], dry_run: bool) -> int:
    rewritten = 0
    for page in _active_markdown_pages(wiki_dir):
        content = read_md(page)
        updated = _rewrite_links_in_content(content, page, wiki_dir, link_map)
        if updated != content:
            rewritten += 1
            print(f"  REWRITE links: {_page_rel(page, wiki_dir)}")
            if not dry_run:
                write_md(page, updated)
    return rewritten


def _apply_plan(wiki_dir: Path, plan: MigrationPlan, dry_run: bool) -> None:
    archive_root = wiki_dir / "legacy" / plan.archive_name

    for target in plan.targets:
        matched_pages = plan.matches.get(target.rel, [])
        for page in matched_pages:
            _archive_page(page, wiki_dir, archive_root, dry_run)
            if page.rel != target.rel:
                _remove_old_page(page, dry_run)
        _write_page(wiki_dir, target.rel, _merge_legacy_notes(target, matched_pages), dry_run)

    for page in plan.unmatched:
        _archive_page(page, wiki_dir, archive_root, dry_run)
        _remove_old_page(page, dry_run)
        print(f"  UNMATCHED archived: {page.rel}")

    _write_page(wiki_dir, "index.md", plan.index_content, dry_run)
    rewritten = _rewrite_active_links(wiki_dir, plan.link_map, dry_run)
    if plan.link_map:
        print(f"  Link mappings: {len(plan.link_map)} path(s); pages rewritten: {rewritten}")

    if not dry_run and plan.manifest is not None:
        plan.manifest.save(wiki_dir)
        print(f"  WRITE {wiki_dir / '.llm-wiki-manifest.json'}")
    elif dry_run:
        print("  DRY-RUN: manifest refresh skipped")


def run(args) -> None:
    src_dir = getattr(args, "src_dir", ".")
    wiki_dir = Path(getattr(args, "wiki_dir", DEFAULT_WIKI_DIR))
    dry_run = getattr(args, "dry_run", False)
    validate_path(src_dir, "--src-dir")
    validate_path(str(wiki_dir), "--wiki-dir")

    if not wiki_dir.exists():
        print(f"Error: Directory {wiki_dir} does not exist.", file=sys.stderr)
        sys.exit(1)

    print(f"{'Planning' if dry_run else 'Migrating'} wiki at: {wiki_dir}")
    print(f"Source directory: {src_dir}")

    plan = _build_migration_plan(wiki_dir, src_dir)
    if dry_run:
        print("DRY-RUN: no files will be modified.")

    _apply_plan(wiki_dir, plan, dry_run)

    print(
        "\nMigration complete: "
        f"{len(plan.targets)} canonical page(s), "
        f"{sum(len(v) for v in plan.matches.values())} archived source page(s), "
        f"{len(plan.unmatched)} unmatched archived page(s)."
    )
