"""Portable installation of the managed LLM Wiki integrity workflow."""

from __future__ import annotations

import hashlib
import hmac
import json
import re
from dataclasses import dataclass
from pathlib import Path

from .io import first_unsafe_path_component, write_bytes_atomic
from .source_selection import (
    SourceSelectionError,
    locate_exact_repository_path,
    resolve_source_selection,
    validate_persisted_source_selection_identity,
)
from .sync_manifest import (
    MANIFEST_FILENAME,
    SyncManifest,
    SyncManifestError,
)
from .validation import require_repository_relative_path
from .wiki_lifecycle import WikiLifecycleState, classify_wiki_lifecycle


MANAGED_WORKFLOW_PATH = Path(".github/workflows/llm-wiki-integrity.yml")
MANAGED_WORKFLOW_SCHEMA = "llm-wiki-install-ci/v1"
CHECKOUT_ACTION_REF = "d23441a48e516b6c34aea4fa41551a30e30af803"
WIKI_INTEGRITY_ACTION = "Denissvgn/python-wiki-llm/integrations/wiki-integrity"

_ACTION_REF_RE = re.compile(r"^[0-9a-fA-F]{40}$", re.ASCII)
_MANAGED_HEADER_RE = re.compile(
    rf"\A# Generated by llm-wiki install-ci; do not edit\.\n"
    rf"# llm-wiki-managed: {re.escape(MANAGED_WORKFLOW_SCHEMA)}\n"
    r"# llm-wiki-content-sha256: ([0-9a-f]{64})\n\n",
    re.ASCII,
)


class InstallCiError(ValueError):
    """Raised when a portable CI workflow cannot be installed safely."""


@dataclass(frozen=True)
class InstallCiResult:
    """Outcome of one workflow installation attempt."""

    path: Path
    operation: str
    action_ref: str
    dry_run: bool

    @property
    def changed(self) -> bool:
        return self.operation != "unchanged" and not self.dry_run


def normalize_action_ref(value: object) -> str:
    """Return a canonical immutable Git commit for the reusable action."""

    if not isinstance(value, str) or _ACTION_REF_RE.fullmatch(value) is None:
        raise InstallCiError("--action-ref must be exactly 40 hexadecimal characters")
    return value.lower()


def _portable_project_path(value: object, *, label: str, allow_root: bool) -> str:
    if value == "." and allow_root:
        return "."
    path = require_repository_relative_path(
        value,
        text_error=InstallCiError(f"{label} must be a non-empty project-relative path"),
        posix_error=InstallCiError(f"{label} must use portable POSIX path spelling"),
        normalized_error=InstallCiError(
            f"{label} must be a normalized project-relative path"
        ),
        absolute_error=InstallCiError(
            f"{label} must be project-relative for a portable workflow"
        ),
        separator_error=InstallCiError(
            f"{label} must use portable POSIX '/' separators"
        ),
        control_error=InstallCiError(f"{label} must not contain control characters"),
        reject_delete_character=True,
        leading_backslash_is_absolute=True,
        portability_error=InstallCiError(
            f"{label} must be portable across supported filesystems"
        ),
    )
    if "${{" in path:
        raise InstallCiError(f"{label} must not contain a GitHub Actions expression")
    return path


def _project_directory(
    project_root: Path,
    relative_path: str,
    *,
    label: str,
) -> Path:
    if relative_path == ".":
        candidate = project_root
    else:
        try:
            candidate = locate_exact_repository_path(project_root, relative_path)
        except SourceSelectionError as exc:
            raise InstallCiError(
                f"{label} is not an exact portable path: {exc}"
            ) from exc
        if candidate is None:
            raise InstallCiError(f"{label} does not name an existing directory")
    unsafe = first_unsafe_path_component(candidate)
    if unsafe is not None:
        try:
            display = unsafe.relative_to(project_root)
        except ValueError:
            display = unsafe
        raise InstallCiError(f"{label} crosses an unsafe path component: {display}")
    try:
        resolved = candidate.resolve()
        resolved.relative_to(project_root)
    except (OSError, RuntimeError, ValueError) as exc:
        raise InstallCiError(f"{label} resolves outside the project") from exc
    if not resolved.is_dir():
        raise InstallCiError(f"{label} does not name an existing directory")
    return resolved


def _validate_default_selection_contract(source_root: Path, wiki_dir: Path) -> None:
    """Prove the managed wiki can use default source-selection discovery."""

    manifest_path = wiki_dir / MANIFEST_FILENAME
    unsafe = first_unsafe_path_component(manifest_path)
    if unsafe is not None or not manifest_path.is_file():
        raise InstallCiError(
            "managed wiki manifest must be a regular file without symlink or "
            "reparse components"
        )
    try:
        manifest = SyncManifest.load(wiki_dir)
        policy = resolve_source_selection(source_root, None)
        validate_persisted_source_selection_identity(
            manifest.generation_inputs,
            None if policy is None else policy.identity,
            operation="install-ci",
        )
    except (
        FileNotFoundError,
        OSError,
        UnicodeError,
        ValueError,
        SourceSelectionError,
        SyncManifestError,
    ) as exc:
        raise InstallCiError(
            f"managed wiki is not valid for default source-selection discovery: {exc}"
        ) from exc


def _workflow_body(*, action_ref: str, src_dir: str, wiki_dir: str) -> str:
    source_value = json.dumps(src_dir)
    wiki_value = json.dumps(wiki_dir)
    return f"""name: LLM Wiki integrity

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  integrity:
    name: LLM Wiki integrity
    runs-on: ubuntu-24.04
    timeout-minutes: 45
    permissions:
      contents: read
    steps:
      - name: Check out the repository without credentials
        uses: actions/checkout@{CHECKOUT_ACTION_REF} # v6.1.0
        with:
          persist-credentials: false

      - name: Check LLM Wiki integrity
        uses: {WIKI_INTEGRITY_ACTION}@{action_ref}
        with:
          src-dir: {source_value}
          wiki-dir: {wiki_value}
"""


def render_managed_workflow(
    *,
    action_ref: str,
    src_dir: str = ".",
    wiki_dir: str = "docs/llm_wiki",
) -> bytes:
    """Render deterministic workflow bytes with a self-verifying owner marker."""

    canonical_ref = normalize_action_ref(action_ref)
    source_path = _portable_project_path(src_dir, label="--src-dir", allow_root=True)
    wiki_path = _portable_project_path(wiki_dir, label="--wiki-dir", allow_root=False)
    body = _workflow_body(
        action_ref=canonical_ref,
        src_dir=source_path,
        wiki_dir=wiki_path,
    )
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    header = (
        "# Generated by llm-wiki install-ci; do not edit.\n"
        f"# llm-wiki-managed: {MANAGED_WORKFLOW_SCHEMA}\n"
        f"# llm-wiki-content-sha256: {digest}\n\n"
    )
    return (header + body).encode("utf-8")


def _normalize_newlines(content: bytes) -> bytes | None:
    try:
        text = content.decode("utf-8")
    except UnicodeDecodeError:
        return None
    return text.replace("\r\n", "\n").replace("\r", "\n").encode("utf-8")


def is_unmodified_managed_workflow(content: bytes) -> bool:
    """Return whether bytes carry a valid installer ownership checksum."""

    normalized = _normalize_newlines(content)
    if normalized is None:
        return False
    text = normalized.decode("utf-8")
    match = _MANAGED_HEADER_RE.match(text)
    if match is None:
        return False
    body = text[match.end() :].encode("utf-8")
    actual = hashlib.sha256(body).hexdigest()
    return hmac.compare_digest(match.group(1), actual)


def _validate_workflow_target(project_root: Path) -> Path:
    target = project_root / MANAGED_WORKFLOW_PATH
    for prefix in (
        ".github",
        ".github/workflows",
        MANAGED_WORKFLOW_PATH.as_posix(),
    ):
        try:
            existing = locate_exact_repository_path(project_root, prefix)
        except SourceSelectionError as exc:
            raise InstallCiError(f"workflow target is not portable: {exc}") from exc
        if existing is None:
            break
    unsafe = first_unsafe_path_component(target)
    if unsafe is not None:
        try:
            display = unsafe.relative_to(project_root)
        except ValueError:
            display = unsafe
        raise InstallCiError(
            f"workflow target crosses an unsafe path component: {display}"
        )
    if target.exists() and not target.is_file():
        raise InstallCiError(
            f"workflow target is not a regular file: {MANAGED_WORKFLOW_PATH}"
        )
    return target


def install_ci_workflow(
    *,
    action_ref: str,
    src_dir: str = ".",
    wiki_dir: str = "docs/llm_wiki",
    dry_run: bool = False,
    force: bool = False,
    project_root: str | Path | None = None,
) -> InstallCiResult:
    """Create or safely update the repository's managed integrity workflow."""

    canonical_ref = normalize_action_ref(action_ref)
    source_path = _portable_project_path(src_dir, label="--src-dir", allow_root=True)
    wiki_path = _portable_project_path(wiki_dir, label="--wiki-dir", allow_root=False)
    try:
        root = (
            Path.cwd().resolve()
            if project_root is None
            else Path(project_root).resolve()
        )
    except (OSError, RuntimeError, ValueError) as exc:
        raise InstallCiError("project root cannot be resolved") from exc
    if not root.is_dir():
        raise InstallCiError("project root must be an existing directory")

    source_root = _project_directory(root, source_path, label="--src-dir")
    managed_wiki = _project_directory(root, wiki_path, label="--wiki-dir")
    state = classify_wiki_lifecycle(managed_wiki)
    if state is not WikiLifecycleState.MANAGED:
        raise InstallCiError(
            "install-ci requires an initialized managed wiki with "
            f"{MANIFEST_FILENAME}; run llm-wiki bootstrap first"
        )
    _validate_default_selection_contract(source_root, managed_wiki)

    desired = render_managed_workflow(
        action_ref=canonical_ref,
        src_dir=source_path,
        wiki_dir=wiki_path,
    )
    target = _validate_workflow_target(root)
    try:
        existing = target.read_bytes() if target.exists() else None
    except OSError as exc:
        raise InstallCiError(
            f"cannot read managed workflow {MANAGED_WORKFLOW_PATH}: {exc}"
        ) from exc
    normalized_existing = (
        _normalize_newlines(existing) if existing is not None else None
    )
    if normalized_existing == desired:
        return InstallCiResult(
            path=MANAGED_WORKFLOW_PATH,
            operation="unchanged",
            action_ref=canonical_ref,
            dry_run=dry_run,
        )

    operation = "create" if existing is None else "update"
    if (
        existing is not None
        and not is_unmodified_managed_workflow(existing)
        and not force
    ):
        raise InstallCiError(
            f"{MANAGED_WORKFLOW_PATH} exists and is not an unmodified "
            "llm-wiki managed workflow; rerun with --force to replace it"
        )

    if not dry_run:
        try:
            write_bytes_atomic(target, desired)
        except OSError as exc:
            raise InstallCiError(
                f"cannot write managed workflow {MANAGED_WORKFLOW_PATH}: {exc}"
            ) from exc
    return InstallCiResult(
        path=MANAGED_WORKFLOW_PATH,
        operation=operation,
        action_ref=canonical_ref,
        dry_run=dry_run,
    )


__all__ = [
    "CHECKOUT_ACTION_REF",
    "InstallCiError",
    "InstallCiResult",
    "MANAGED_WORKFLOW_PATH",
    "MANAGED_WORKFLOW_SCHEMA",
    "WIKI_INTEGRITY_ACTION",
    "install_ci_workflow",
    "is_unmodified_managed_workflow",
    "normalize_action_ref",
    "render_managed_workflow",
]
